export const projectsList = [
  {
    id: 1,
    name: "BMI Calculator",
    image: "/images/bmicalculator.png",
    link: "https://bmicalculatorr.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Projects/tree/main/bmicalculator",
    project: "bmicalculator",
    tools: ["React"],
  },
  {
    id: 2,
    name: "Crypto App",
    image: "/images/crypto.png",
    link: "https://crypto-app-binance.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Projects/tree/main/crypto-app",
    project: "crypto-app",
    tools: ["React"],
  },
  {
    id: 3,
    name: "Rock Paper Scissors Game",
    image: "/images/rockpaperscissorsgame.png",
    link: "https://rock-paper-scissors-game1.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Projects/tree/main/rock-paper-scissors-game",
    project: "rock-paper-scissors-game",
    tools: ["React"],
  },
  {
    id: 4,
    name: "Typing Speed App",
    image: "/images/typingspeed.png",
    link: "https://typing-speed-app.vercel.app",
    GitHub: "https://github.com/eraydmrcoglu/Projects/tree/main/typing-speed-app",
    project: "typing-speed-app",
    tools: ["React"],
  },
];
