export const LIST_MOCK = {
  data: {
    characters: {
      results: [
        {
          id: "1",
          name: "Rick Sanchez",
          status: "Alive",
          species: "Human",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
          origin: {
            id: "1",
            name: "Earth (C-137)",
            dimension: "Dimension C-137",
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },
        },
        {
          id: "2",
          name: "Morty Smith",
          status: "Alive",
          species: "Human",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
          origin: {
            id: "1",
            name: "Earth (C-137)",
            dimension: "Dimension C-137",
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },
        },
        {
          id: "3",
          name: "Summer Smith",
          status: "Alive",
          species: "Human",
          type: "",
          gender: "Female",
          image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
          origin: {
            id: "20",
            name: "Earth (Replacement Dimension)",
            dimension: "Replacement Dimension",
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },
        },
        {
          id: "4",
          name: "Beth Smith",
          status: "Alive",
          species: "Human",
          type: "",
          gender: "Female",
          image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
          origin: {
            id: "20",
            name: "Earth (Replacement Dimension)",
            dimension: "Replacement Dimension",
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },        
        },
        {
          id: "5",
          name: "Jerry Smith",
          status: "Alive",
          species: "Human",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
          origin: {
            id: "20",
            name: "Earth (Replacement Dimension)",
            dimension: "Replacement Dimension",
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },
        },
        {
          id: "6",
          name: "Abadango Cluster Princess",
          status: "Alive",
          species: "Alien",
          type: "",
          gender: "Female",
          image: "https://rickandmortyapi.com/api/character/avatar/6.jpeg",
          origin: {
            id: "2",
            name: "Abadango",
            dimension: "unknown",
          },
          location: {
            id: "2",
            name: "Abadango",
          },
        },
        {
          id: "7",
          name: "Abradolf Lincler",
          status: "unknown",
          species: "Human",
          type: "Genetic experiment",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
          origin: {
            id: "20",
            name: "Earth (Replacement Dimension)",
            dimension: "Replacement Dimension",
          },
          location: {
            id: "21",
            name: "Testicle Monster Dimension",
          },
        },
        {
          id: "8",
          name: "Adjudicator Rick",
          status: "Dead",
          species: "Human",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: "3",
            name: "Citadel of Ricks",
          },
        },
        {
          id: "9",
          name: "Agency Director",
          status: "Dead",
          species: "Human",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/9.jpeg",
          origin: {
            id: "20",
            name: "Earth (Replacement Dimension)",
            dimension: "Replacement Dimension",
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },
        },
        {
          id: "10",
          name: "Alan Rails",
          status: "Dead",
          species: "Human",
          type: "Superhuman (Ghost trains summoner)",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/10.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: "4",
            name: "Worldender's lair",
          },
        },
        {
          id: "11",
          name: "Albert Einstein",
          status: "Dead",
          species: "Human",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/11.jpeg",
          origin: {
            id: "1",
            name: "Earth (C-137)",
            dimension: "Dimension C-137",
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },
        },
        {
          id: "12",
          name: "Alexander",
          status: "Dead",
          species: "Human",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/12.jpeg",
          origin: {
            id: "1",
            name: "Earth (C-137)",
            dimension: "Dimension C-137",
          },
          location: {
            id: "5",
            name: "Anatomy Park",
          },
        },
        {
          id: "13",
          name: "Alien Googah",
          status: "unknown",
          species: "Alien",
          type: "",
          gender: "unknown",
          image: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },
        },
        {
          id: "14",
          name: "Alien Morty",
          status: "unknown",
          species: "Alien",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/14.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: "3",
            name: "Citadel of Ricks",
          },
        },
        {
          id: "15",
          name: "Alien Rick",
          status: "unknown",
          species: "Alien",
          type: "",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/15.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: "3",
            name: "Citadel of Ricks",
          },
        },
        {
          id: "16",
          name: "Amish Cyborg",
          status: "Dead",
          species: "Alien",
          type: "Parasite, Cyborg",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/16.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: "20",
            name: "Earth (Replacement Dimension)",
          },
        },
        {
          id: "17",
          name: "Annie",
          status: "Alive",
          species: "Human",
          type: "",
          gender: "Female",
          image: "https://rickandmortyapi.com/api/character/avatar/17.jpeg",
          origin: {
            id: "1",
            name: "Earth (C-137)",
            dimension: "Dimension C-137",
          },
          location: {
            id: "5",
            name: "Anatomy Park",
          },
        },
        {
          id: "18",
          name: "Antenna Morty",
          status: "Alive",
          species: "Human",
          type: "Human with antennae",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/18.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: "3",
            name: "Citadel of Ricks",
          },
        },
        {
          id: "19",
          name: "Antenna Rick",
          status: "unknown",
          species: "Human",
          type: "Human with antennae",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/19.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: null,
            name: "unknown",
          },
        },
        {
          id: "20",
          name: "Ants in my Eyes Johnson",
          status: "unknown",
          species: "Human",
          type: "Human with ants in his eyes",
          gender: "Male",
          image: "https://rickandmortyapi.com/api/character/avatar/20.jpeg",
          origin: {
            id: null,
            name: "unknown",
            dimension: null,
          },
          location: {
            id: "6",
            name: "Interdimensional Cable",
          },
        },
      ],
      info: {
        pages: 25,
        next: 2,
        prev: null,
        count: 493,
      },
    },
  },
};

export const DETAILS_MOCK = {
  data: {
    character: {
      id: "1",
      name: "Rick Sanchez",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      origin: {
        id: "1",
        name: "Earth (C-137)",
        dimension: "Dimension C-137",
      },
      location: {
        id: "20",
        name: "Earth (Replacement Dimension)",
      },
    },
  },
};
